name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Run PurgeCSS
      run: npx purgecss --css src/css/*.css --content src/**/*.html --output dist/css/

    - name: Minify JS
      run: npm run minify:js

    - name: Minify CSS
      run: npm run minify:css

    - name: Minify HTML
      run: npm run minify:html

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
